### PR TITLE
adding link

### PR DESCRIPTION
**Pull request by IshaanXCoder**
[LINK](https://codedamn.com/project/solution/615831a5bd24a00009282320)

### CODE REVIEW

**Comment by ishikkkkaaaa** [comment]
@IshaanXCoder  Congratulations on your submission, you did a fantastic job.
Please share your Email ID, our team will reach out to you by the end of this contest, after checking your code.

Till then do go through our courses, on https://codedamn.com/courses

Happy learning!

**Comment by IshaanXCoder** [comment]
> @IshaanXCoder  Congratulations on your submission, you did a fantastic job.
> Please share your Email ID, our team will reach out to you by the end of this contest, after checking your code.
> 
> Till then do go through our courses, on https://codedamn.com/courses
> 
> Happy learning!



kesarwaniishaan4@gmail.com

**Comment by IshaanXCoder** [comment]
kesarwaniishaan4@gmail.com

**Comment by ishikkkkaaaa** [comment]
Hey please edit your folder, and followup the Template guidelines

create a new file as follows: `submission_your_github_username.html` inside your chosen topic folder and send the PR using the following template:

👉   <b>Name of the file: </b> <i>your_github_username.html</i><br/>
👉   <b>Inside the file, paste your codedamn's submission URL. </b> The format is: <i>`https://codedamn.com/project/solution/:id`</i><br/>
👉   <b>Write your Email ID, Github username, and name<br/>
👉   <b>Send a Pull Request</b> to `main` branch<br/>

**Pull request merged**
