### PR TITLE
2 submissions - [Astral Portfolio Page] & [HTML5 Massively Landing Page]

### PR DESCRIPTION
**Pull request by SubhanshuMG**

### CODE REVIEW

**Comment by SubhanshuMG** [comment]
Added 2 projects 

1. Astral Landing Page
2. Massively Landing Page

**Comment by ishikkkkaaaa** [comment]
@SubhanshuMG please follow the following Template format, you don't have to post the code.

In the `Submission projects` directory, create a new file as follows: `submission_your_github_username.html` inside your chosen topic folder and send the PR using the following template:

👉   <b>Name of the file: </b> <i>your_github_username.html</i><br/>
👉   <b>Inside the file, paste your codedamn's submission URL. </b> The format is: <i>`https://codedamn.com/project/solution/:id`</i><br/>
👉   <b>Send a Pull Request</b> to `main` branch<br/>

**Comment by SubhanshuMG** [comment]
@ishikkkkaaaa removed the code and included only the HTML file with the link.

**Comment by SubhanshuMG** [comment]
@ishikkkkaaaa removed the code and included only the HTML file with the link. Do check it.

**Comment by ishikkkkaaaa** [comment]
@SubhanshuMG pl check the URL, its not working.

**Comment by SubhanshuMG** [comment]
> @SubhanshuMG pl check the URL, its not working.

it's working on my end... just copy and paste the URL on the address bar, it'll work

**Comment by deepxcode** [comment]
@SubhanshuMG 
Congratulations on your submission, you did a fantastic job. Our team will reach out to you by the end of this contest, after checking your code.
Till then do go through our courses, on https://codedamn.com/courses
Happy learning!

**Pull request merged**
