### PR TITLE
Hulu Clone Project

### PR DESCRIPTION
**Pull request by nandirishav**
Solution URL - https://codedamn.com/project/solution/615720d7dbe0bc0009e4bf4d

### CODE REVIEW

**Comment by nandirishav** [comment]
I have added the email id along with the submission url as directed . @ishikkkkaaaa

**Comment by ishikkkkaaaa** [comment]
Hey, please follow up the updated template.

Sorry for the inconvenience caused

create a new file as follows: `submission_your_github_username.html` inside your chosen topic folder and send the PR using the following template:

👉   <b>Name of the file: </b> <i>your_github_username.html</i><br/>
👉   <b>Inside the file, paste your codedamn's submission URL. </b> The format is: <i>`https://codedamn.com/project/solution/:id`</i><br/>
👉   <b>Write your Email ID, Github username, and name<br/>
👉   <b>Send a Pull Request</b> to `main` branch<br/>

**Comment by nandirishav** [comment]
I have added the github username and name as directed , is it okay now ? @ishikkkkaaaa

**Comment by nandirishav** [comment]
Please tell me if there is any correction required , a little response would be helpful  @ishikkkkaaaa

**Comment by deepxcode** [comment]
@nandirishav 
Congratulations on your submission, you did a fantastic job. Our team will reach out to you by the end of this contest, after checking your code.
Till then do go through our courses, on https://codedamn.com/courses
Happy learning!

**Pull request merged**
